x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: sampledb
  REACT_APP_SERVER_PORT: 8000

services:
  server:
    build: ./server
    container_name: node_server_container
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    command: npm start
  client:
    build: ./client
    container_name: client_container
    ports:
      - 3000:3000
    command: npm start