services:
  client:
    build: ./client
    ports:
      - "3000:3000"

  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    links:
      - postgres
    restart: always

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres # The PostgreSQL default database (automatically created at first launch)
    ports:
      - "5432:5432"
    volumes:
          # copy the sql script to create tables
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
          # copy the sql script to fill tables 
          - ./db/populate.sql:/docker-entrypoint-initdb.d/populate.sql
    restart: always
  